# -*- coding: utf-8 -*-
"""D22CS051_Q9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuE5daiKOAuUHVKzNxQG0rR-TW7ABoCV
"""

# importing libs
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np

# downloading image
url1 = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Lesser_whistling_duck_%28Dendrocygna_javanica%29_from_Bahour_lake%2C_Pondy_IMG_4162_.jpg/640px-thumb.jpg"
!wget {url1} -O "1_image.jpg"

# reading image in grayscale and calculate hist.
img = cv.imread('1_image.jpg', cv.IMREAD_GRAYSCALE)
hist = cv.calcHist([img],[0],None,[10],[0,256])
hist.shape

# showing results (image and histogram)
plt.figure(figsize=(12,7)) # plot setup
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray") # plot image
plt.axis("off")
plt.subplot(1,2,2)
plt.plot(hist) # plot graph
plt.xlim([0,10])
plt.show()

img_equalized = cv.equalizeHist(img)
hist = cv.calcHist([img_equalized],[0],None,[10],[0,256])

# showing results (image and histogram)
plt.figure(figsize=(12,7)) # plot setup
plt.subplot(1,2,1)
plt.imshow(img_equalized,cmap="gray") # plot image
plt.axis("off")
plt.subplot(1,2,2)
plt.plot(hist) # plot graph
plt.xlim([0,10])
plt.show()

# reading same image in bgr.
img = cv.imread('1_image.jpg')
color = ('b','g','r')
plt.figure(figsize=(12,7)) # plot setup
plt.subplot(1,2,1)
plt.imshow(img[:,:,::-1]) # plot image
plt.axis("off")
plt.subplot(1,2,2)
for i,col in enumerate(color): # loop for color channels
    histr = cv.calcHist([img],[i],None,[10],[0,256])
    plt.plot(histr,color = col) # ploting plot with c = (b,g,r)
    plt.xlim([0,10])
plt.show()