# -*- coding: utf-8 -*-
"""D22CS051_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12etVY-YeLdKV4xPHZntHO_3w9mp_jPHM
"""

# installing system depencies
!apt install tesseract-ocr -y

# importing libs
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np
try:
  import pytesseract
except:
  !pip -q install pytesseract
import pytesseract
from PIL import Image

from google.colab import files

file = files.upload()

img = cv.imread("india-map.jpg",0)
img.shape

plt.figure(figsize=(15,15))
_,img = cv.threshold(img,127,255,cv.THRESH_BINARY)
plt.imshow(img,"gray")
plt.show()

data = pytesseract.image_to_data(img).split("\n")

# data

# state_1_idx,state_2_idx = data.index('5\t1\t13\t1\t38\t1\t172\t626\t60\t11\t14\tBengal'),data.index('5\t1\t13\t1\t13\t1\t186\t213\t41\t34\t40\tDELHI"')
state_1_idx,state_2_idx = data.index('5\t1\t13\t1\t21\t1\t33\t349\t81\t30\t52\tGandhinagary'),data.index('5\t1\t13\t1\t31\t1\t233\t519\t54\t16\t95\tHyderabad')

st_1_x,st_1_y = int(data[state_1_idx].split('\t')[6]),int(data[state_1_idx].split('\t')[7])
st_2_x,st_2_y = int(data[state_2_idx].split('\t')[6]),int(data[state_1_idx].split('\t')[7])
st_1_x,st_1_y,st_2_x,st_2_y

# cal. distance b/w st_1 st_2
distance = np.linalg.norm([st_1_x - st_2_x, st_1_y - st_2_y])
distance

# dist = ((st_2_y-st_1_y)**2 + (st_2_x-st_1_x)**2)**0.5
# dist

print(f"the distance between Gandhi nagat to Hyderabad is: {distance} units")