# -*- coding: utf-8 -*-
"""D22CS051_Q10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18c0vsGMFcSQs4hYMefndkqk-XpVqvu_0
"""

!apt install tesseract-ocr -y

# importing libs
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np
try:
  import pytesseract
except:
  !pip3 -q install pytesseract

import pytesseract

"""**`please restart runtime as new dependecy has been installed!!!`**"""

img_1 = cv.imread("img_1.png",0)
img_2 = cv.imread("img_2.png",0)
img_1.shape,img_2.shape

plt.imshow(img_1,cmap="gray")
plt.axis("off")
plt.show()
print(f"The last 3 digits of the phone number are: {pytesseract.image_to_string(img_1)[7:]}.")

plt.imshow(img_2,cmap="gray")
plt.axis("off")
plt.show()
print(f"The last 3 digits of the phone number are: {pytesseract.image_to_string(img_2)[7:]}.")